intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{ctre}: {hxx ixx txx}{**} $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
# hxx{version}: in{version} $src_root/manifest
# {
#   dist  = true
#   clean = ($src_root != $out_root)
# }

# Build options.
#
cxx.poptions =+ "-I$src_base"

# Export options.
#
lib{ctre}:
{
  cxx.export.poptions = "-I$src_base"
  cxx.export.libs = $intf_libs
}

# Install into, say, /usr/include/ recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
